### ISSUE TITLE
Intuition behind setting extra lane candidates to be 0

### ISSUE THREAD

**Issue by ArielleZhang** [d1024choi/HLSTrajForecast#4]
Hi,

Thanks for the great, inspiring work! I was going over the code specifically want to understand how the CVAE is using lane candidates to predict, however I see for the default training on Argoverse, the `num_max_paths` is set to be 10 and for the cases where there are fewer lane candidates, the rest lane place holders are set to be 0 zero tensors and then it obtained the lane embeddings of this 0 tensor in `LaneEncoder`, `HLS.py`. Is there an intuition of conditioning on an embedding of a 0 tensor? How does that alleviate the mode blur issue mentioned in the paper? Appreciate your help!

Thanks,

Arielle Zhang

**Comment by d1024choi** [comment]
[ArielleZhang](https://github.com/ArielleZhang) 
Thanks for your interest in our work. The zero embedding for the fake lanes was intended such that 'mode selection network' could easily differentiate the fake lanes from the real ones so that the probability of selecting the fake lane becomes zero during the inference.

**Comment by ArielleZhang** [comment]
Hi,

Thanks for the response, but the lane candidates are used to produce the z low, which I believe should be the representation of the future trajectory distribution over this specific lane candidate. If I'm understanding correctly, we just completely ignore the z low if the lane is fake because in the mode selector step it will be ignore anyways.

Thanks,

Arielle

**Comment by d1024choi** [comment]
[ArielleZhang](https://github.com/ArielleZhang)

Regarding producing the low-level z, the fake lane will never be used during the training because, in nuScenes and Argoverse dataset, every vehicle is assigned a real lane as a ground-truth. This means that the low-level z will never be conditioned with the fake lane during the training.

Regarding the inference with the low-level z conditioned with the fake lane, I am uncertain how the trained model will produce trajectories with the z. I found from the experiments that the trajectories generated with the z often sprawl. This might have a bad effect on the prediction performance when the model selection network gives a high score to the fake lane.
